---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart php-fpm
  ansible.builtin.service:
    name: "php{{ nextcloud_php_version }}-fpm"
    state: restarted
